-- -- Department
-- INSERT INTO Department
-- 	(budget, supervisor_id)
-- VALUES
-- 	()

-- -- Employee
-- INSERT INTO Employee
-- 	(department_id)
-- VALUES
-- 	()
-- 	
-- -- Computer
-- INSERT INTO Computer
-- 	(purchase_date, decommission_date, owner_id)
-- VALUES
-- 	()
-- 	
-- -- Training_Program
-- INSERT INTO Training_Program
-- 	(start_date, end_date, maximum_attendees)
-- VALUES
-- 	()
-- 	
-- -- Employee_Program
-- INSERT INTO Employee_Program
-- 	(employee_id, training_program_id)
-- VALUES
-- 	()
-- 	
-- -- Product_Type
-- INSERT INTO Product_Type
-- 	(category)
-- VALUES
-- 	()
-- 	
-- -- Customer
-- INSERT INTO Customer
-- 	(first_name, last_name, date_created, days_active)
-- VALUES
-- 	()
-- 	
-- -- Product
-- INSERT INTO Product
-- 	(type_id, price, title, description, creator_id)
-- VALUES
-- 	()
-- 	
-- -- Order
-- INSERT INTO "Order"
-- 	(customer_id)
-- VALUES
-- 	()
-- 	
-- -- Payment_Type
-- INSERT INTO Payment_Type
-- 	(account_number)
-- VALUES
-- 	()
-- 	
-- -- Order_Payment
-- INSERT INTO Order_Payment
-- 	(order_id, payment_type_id)
-- VALUES
-- 	()
-- 	
-- -- Customer_Payment
-- INSERT INTO Customer_Payment 
-- 	(customer_id, payment_type_id)
-- VALUES
-- 	()
-- 	